Description: >
  Micah Shallom Bawa
  Project Two: Server Stack Creation consisting of servers, gateways and IAM systems management

#Parameter Template
Parameters:
  AMItoUse:
    Description: AMI to create for our image
    Type: String
  ProjectName:
    Description: Environment Name for all project infrastructures
    Type: String

Resources:
#Creating an IAM Role to allow access to our EC2 instance via session manager
  RoleForSessionAccess: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "root"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles: 
        - Ref: RoleForSessionAccess
#InstanceProfile which connects the IAM Role to the EC2 server instance
  ServerInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - Ref: RoleForSessionAccess
############################################################################
#SecurityGroup For the EC2 server instance
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
      - Fn::ImportValue: 
          !Sub "${ProjectName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: !Ref AMItoUse
      KeyName: vockey
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet: 
          - Ref: "WebSecurityGroup"
        SubnetId: 
          - Fn::ImportValue: !Sub "${ProjectName}-PRIV-SUBNET"